FS05-PART4-TEAM2/5-fav_moving-team2-be

- .github/workflows/deploy.yml
- src/app.module.ts
> infra: ec2 배포 설정

- src/common/exceptions/invalid-credentials.exception.ts
- src/customer/auth/auth.service.ts
-  로그인 시 이메일., 비밀번호 검증하는 exception 생성  
- 이메일, 비밀번호 중 어떤것이 틀렸는지 알수 없게 하였음
> add excemption

- src/customer/auth/auth.controller.ts
- src/mover/auth/auth.controller.ts
> modifying API Path

- src/app.module.ts
- src/auth/auth.module.ts
- src/auth/auth.service.spec.ts
- src/auth/auth.service.ts
- src/common/utils/set-auth-cookies.util.ts
- src/customer/auth/auth.controller.ts
- src/customer/auth/auth.module.ts
- src/customer/auth/auth.service.ts
- src/mover/auth/auth.controller.ts
- src/mover/auth/auth.module.ts
- src/mover/auth/auth.service.ts
- 모듈 임포트 수정, 토큰 생성 로직 공통 로직으로 처리
> changed token generation logic to common logic

- src/customer/auth/auth.controller.ts
- src/customer/auth/auth.service.ts
- src/customer/controllers/customer-profile.controller.ts
- src/customer/customer.entity.ts
- src/customer/dto/customer-profile.response.dto.ts
- src/customer/services/customer-profile.service.ts
- 손님 프로필 등록/수정 API 개발 `PUT api/profile/cusomter`
content-type 유의해 주세요.
```
Content-Type: multipart/form-data
```
> feat: 손님 프로필 등록/수정 API

- src/auth/auth.controller.ts
- src/common/constants/quotation-state.constant.ts
- src/common/guards/jwt-cookie-auth.guard.ts
- src/quotation/quotation.entity.ts
- src/quotation/quotation.service.ts
> 견적 요청 enum 지정 

- src/customer/controllers/customer-profile.controller.ts
- src/customer/services/customer-profile.service.ts
- src/mover/controllers/mover-profile.controller.ts
- src/mover/services/mover-profile.service.ts
- 일반 유저 프로필 정보 조회 `GET api/profile/customer` 구현
- 기사 프로필 정보 조회 `GET api/profile/mover` 구현
> feat: GET customer/mover profile 구현

- src/app.module.ts
- src/quotation/quotation.controller.ts
- src/received-quotation/dto/received-quotation.response.dto.ts
- src/received-quotation/received-quotation.controller.ts
- src/received-quotation/received-quotation.entity.ts
- src/received-quotation/received-quotation.module.ts
- src/received-quotation/received-quotation.service.ts
- 받은 견적 조회 ( 진행중인 견적, 받았던견적 )
- 받은 견적 확정하기 ( 확정하면 관련 요청 전부 받았던 상태로 이동, 확정 시 견적테이블의 원본 견적 최신화 됨 )
받은 요청 확정 후 원본 견적 조회
> 일반유저: 받은견적 조회 , 견적 확정하기

- src/app.module.ts
- src/mock-api/mock-api.module.ts
- src/mock-api/mock.controller.ts
- src/mock-api/mock/received-quotation.mock.ts
- src/received-quotation/dto/received-quotation.response.dto.ts
- 데이터 생성 없이 mock 전용  api 임시 생성
> Mock API 요청 

- src/receivedQuotation/receivedQuotation.entity.ts
> add entity

- src/common/exceptions/invalid-quotation.exception.ts
- src/common/exceptions/invalid-user.exception.ts
- src/quotation/controllers/mover-quotation.controller.ts
- src/quotation/dtos/create-received-quotation.request.dto.ts
- src/quotation/dtos/get-quotation-list.request.dto.ts
- src/quotation/dtos/quotation.response.dto.ts
- src/quotation/dtos/received-quotation.response.dto.ts
- src/quotation/services/mover-quotation.service.ts
> feat: 받은 요청(기사님) 견적 보내기 API 구현

- src/moverReview/moverReview.controller.ts
- req.user 없을 때 타입 분기 처리를 안했었던 부분 수정
> fix: 비로그인 시 타입 에러 해결

- src/quotation/controllers/assign-quotation.controller.ts
- src/quotation/controllers/mover-quotation.controller.ts
- src/quotation/dtos/reject-assign-quote.request.dto.ts
- src/quotation/services/assign-quotation.service.ts
> feat: 받은 요청(기사님) 반려하기 API 구현

- src/common/dto/pagination.dto.ts
- src/quotation/controllers/mover-quotation.controller.ts
- src/quotation/dtos/get-sent-quotation.response.ts
- src/quotation/services/mover-quotation.service.ts
- 기사님의 보낸 견적 리스트 조회 API 구현
- 관련 API 정보는 노션 및 Swagger 문서에 작성해두었습니다.
> 기사 - 보낸 견적 리스트 조회

- src/quotation/controllers/mover-quotation.controller.ts
- src/quotation/dtos/get-sent-quotation.response.ts
- src/quotation/services/mover-quotation.service.ts
- 기사가 보낸 견적 요청 상세 보기 API 1차 구현
> 기사가 보낸 견적 요청 상세보기

- src/quotation/controllers/assign-quotation.controller.ts
- src/quotation/controllers/mover-quotation.controller.ts
- src/quotation/dtos/get-rejected-Data.response.dto.ts
- src/quotation/services/assign-quotation.service.ts
- 반려 요청 리스트 조회 API 1차 구현
- 관련 문서는 API 명세에 작성해두었습니다.
- 중점적으로 확인해줬으면 하는 로직/파일/의문점 등을 작성해주세요.
(예: useAuth 훅 내부 로직 흐름 자연스러운지 확인 부탁드립니다)
- UI 변경이 있거나 API 응답 결과를 보여주고 싶다면 스크린샷을 첨부해주세요.
> 반려 요청 리스트 조회 API 1차 구현

- src/moverReview/moverReview.service.ts
- 기사 리뷰 리스트 조회 시 totalCount 잘못 출력되는 문제 해결
> fix: 기사 리뷰 리스트 조회 시 totalCount 잘못 출력되는 문제 해결

- src/quotation/services/mover-quotation.service.ts
> fix: 기사 보낸 견적 리스트 페이지네이션 문제 해결

- src/quotation/services/assign-quotation.service.ts
- 반려한 요청 리스트 (기사) 페이지네이션 문제 해결
> fix: 반려한 요청 리스트 (기사) 페이지네이션 문제 해결

- src/likeMover/likeMover.controller.ts
- src/likeMover/likeMover.service.ts
- 찜한 기사님 리스트에서 서비스의 타입이 string이었던 점 수정
```
{
"success": true,
"data": {
"list": [
{
"id": "1503b09e-41a3-48f7-af15-7643e8c1a38d",
"idNum": 13,
"nickName": null,
"profileImage": "http://img1.kakaocdn.net/thumb/R640x640.q70/?fname=http://t1.kakaocdn.net/account_images/default_profile.jpeg",
"serviceList": [
"SMALL_MOVE",
"BIG_MOVE"
],
"likeCount": 8,
"totalRating": 3,
"reviewCounts": 55,
"intro": null,
"career": 1,
"confirmedCounts": 0,
"isLiked": true,
"isAssigned": true
},
{
"id": "78c01b52-538e-4f18-a5f9-dca27ea4214f",
"idNum": 12,
"nickName": null,
"profileImage": null,
"serviceList": null,
"likeCount": 2,
"totalRating": null,
"reviewCounts": 0,
"intro": null,
"career": 11,
"confirmedCounts": 0,
"isLiked": true,
"isAssigned": false
},
{
"id": "8afcbca0-ce76-4734-b238-2a060eed1b59", …
```
> fix: 찜한 기사님 리스트 response에서 서비스 리스트의 타입이 string이었던 부분을 배열로 수정

- src/moverReview/moverReview.service.ts
작성 가능 리뷰 조회 서비스 로직변경
시간 기반 조회 => quotation.state = COMPLETED
>  change reviewavle inquiry service based on state

- src/mover/mover.module.ts
- src/mover/services/mover-info.service.ts
- 기사 상세 조회 및 리스트 조회에서 isAssigned가 현재 손님의 견적중에 활성화 상태일 때만 true로 설정
> fix: 기사 상세 조회 및 리스트 조회에서 isAssigned가 현재 손님의 견적중에 활성화 상태일 때만 true로 설정

- src/common/guards/just-look-user.guard.ts
- src/common/guards/jwt-cookie-auth.guard.ts
- src/customer/auth/auth.service.ts
- src/main.ts
- src/mover/auth/auth.service.ts
- production 환경 인가 분기처리 (쿠키 기반)
- accessToken
- refreshToken
- 위와 같은 형식으로 쿠키에 저장됩니다.
@HEES56
> feat: production 환경 인가 분기처리 (쿠키 기반)

- src/app.module.ts
- src/common/interceptors/loggin.interceptor.ts
- src/database/database.module.ts
> api 및 sql 쿼리 로그 남기기

- src/app.module.ts
- src/common/interceptors/loggin.interceptor.ts
- src/database/database.module.ts
- 이번 PR의 목적과 주요 변경사항을 간단히 작성해주세요.
(예: 로그인 API 호출 시 토큰 저장 방식 변경)
- 개발 중 발견한 이슈, 주의할 점, 공통으로 알아야 할 내용이 있다면 적어주세요.
(예: 이 PR 이후 로그인 상태 확인 방식이 변경되었으니 참고)
- 중점적으로 확인해줬으면 하는 로직/파일/의문점 등을 작성해주세요.
(예: useAuth 훅 내부 로직 흐름 자연스러운지 확인 부탁드립니다)
- UI 변경이 있거나 API 응답 결과를 보여주고 싶다면 스크린샷을 첨부해주세요.
> dev to main

- src/main.ts
> feat: url에 슬래시 제거

- src/mover/services/mover-info.service.ts
- 기사 상세 조회시 지정 견적 요청으로 무조건 뜨는현상 해결 시도
> fix: 기사 상세 조회시 지정 견적 요청으로 무조건 뜨는현상 해결 시도

- src/common/dto/signup.request.dto.ts
지역별 번호 현황
• 02: 서울
• 031: 경기
• 032: 인천
• 033: 강원
• 041: 충남
• 042: 대전
• 043: 충북
• 044: 세종
• 051: 부산
• 052: 울산
• 053: 대구
• 054: 경북
• 055: 경남
• 061: 전남
• 062: 광주
• 063: 전북
• 064: 제주
휴대폰 
010, 011, 016, 017, 018, 019, 070
> 회원가입 시 지역별 번호 추가

- src/database/migrations/1750751645306-Migration.ts
- src/notifications/dto/notification.response.dto.ts
- src/notifications/notification.controller.ts
- src/notifications/notification.entity.ts
- src/notifications/notification.service.ts
- src/quotation/services/assign-quotation.service.ts
- src/quotation/services/customer-quotation.service.ts
- src/quotation/services/mover-quotation.service.ts
- src/task/task.service.ts
> chore: 알림 응답에 견적 id 추가

- src/auth/auth.service.ts
> fix: 쿠키 만료시간 중첩 에러 해결

- src/auth/auth.controller.ts
- refresh 컨트롤러에 refreshToken Body값으로 옵셔널 담을 수 있게 처리
> feat: refresh 컨트롤러에 refreshToken Body값으로 옵셔널 담을 수 있게 처리

- src/mover/services/mover-info.service.ts
- 기사 상세 조회 시 지정 요청인지 여부 확인할 때 최신 데이터 기준으로 잡기
> fix: 기사 상세 조회 시 지정 요청인지 여부 확인할 때 최신 데이터 기준으로 잡기

- src/quotation/services/assign-quotation.service.ts
> fix: 지정 기사 요청 반려 수정 테스트

- src/quotation/services/customer-quotation.service.ts
- 받았던 견적 상세, 리스트에서 총점으로 평점이 표기되었던 문제 수정
> Fix/받았던 견적 상세, 리스트에서 총점으로 평점이 표기되었던 문제 수정

- src/task/task.service.ts
- 기존 로직대로 수정
- 기존에 다음날에 이사 완료 처리되는게 맞는 것 같아서 원래 로직으로 수정합니다.
> fix: 기존 로직대로 수정
